# Generated by Django 5.1.15 on 2026-09-03 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomogeneousMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.CharField(max_length=64, verbose_name='材料代碼')),
                ('name', models.CharField(max_length=255, verbose_name='材料名稱')),
                ('mass_g', models.FloatField(default=0.0, verbose_name='材料質量 (g)')),
                ('total_concentration_pct', models.FloatField(default=0.0, verbose_name='總揭露濃度 (%)')),
                ('mass_balance_valid', models.BooleanField(default=False, verbose_name='質量平衡合格 (98%~102%)')),
            ],
            options={
                'verbose_name': '均質材料',
                'verbose_name_plural': '均質材料拆解',
            },
        ),
        migrations.CreateModel(
            name='RegulatoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation', models.CharField(choices=[('EU RoHS', 'EU RoHS 指令'), ('REACH SVHC', 'EU REACH 候選清單'), ('PFAS', 'PFAS 全氟與多氟烷基物質'), ('China RoHS', '中國 RoHS'), ('Prop 65', '加州 65 號法案')], max_length=64, verbose_name='法規名稱')),
                ('version', models.CharField(default='2026.09', max_length=64, verbose_name='法規版本')),
                ('substance_name', models.CharField(max_length=255, verbose_name='管制物質名稱')),
                ('cas', models.CharField(db_index=True, max_length=32, verbose_name='CAS 號碼')),
                ('threshold_pct', models.FloatField(blank=True, null=True, verbose_name='濃度門檻 (%)')),
                ('is_svhc', models.BooleanField(default=False, verbose_name='是否為 REACH SVHC')),
                ('is_pfas', models.BooleanField(default=False, verbose_name='是否為 PFAS')),
                ('exemption_code', models.CharField(blank=True, max_length=64, verbose_name='適用豁免條款')),
                ('notes', models.TextField(blank=True, verbose_name='法規條文 / 備註說明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
            ],
            options={
                'verbose_name': '法規規則',
                'verbose_name_plural': '法規規則庫',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(max_length=64, unique=True, verbose_name='供應商代碼')),
                ('name', models.CharField(max_length=255, verbose_name='供應商名稱')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='聯絡 Email')),
                ('quality_score', models.FloatField(default=100.0, verbose_name='資料品質評分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '供應商',
                'verbose_name_plural': '供應商清單',
            },
        ),
        migrations.CreateModel(
            name='SubstanceDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cas', models.CharField(db_index=True, max_length=32, verbose_name='CAS 號碼')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='物質名稱')),
                ('concentration_pct', models.FloatField(verbose_name='揭露濃度 (%)')),
                ('concentration_ppm', models.FloatField(default=0.0, verbose_name='計算濃度 (ppm)')),
                ('pfas_intentional_use', models.CharField(default='Unknown', max_length=32, verbose_name='PFAS 刻意添加')),
                ('evidence_status', models.CharField(default='None', max_length=64, verbose_name='佐證文件狀態')),
                ('rohs_eval', models.CharField(default='Approved', max_length=32, verbose_name='RoHS 判定')),
                ('reach_eval', models.CharField(default='Approved', max_length=32, verbose_name='REACH 判定')),
                ('pfas_eval', models.CharField(default='Approved', max_length=32, verbose_name='PFAS 判定')),
                ('action_required', models.TextField(blank=True, verbose_name='系統行動指示')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substances', to='fmd_core.homogeneousmaterial', verbose_name='所屬材料')),
            ],
            options={
                'verbose_name': '物質宣告',
                'verbose_name_plural': '物質明細清單',
            },
        ),
        migrations.CreateModel(
            name='SupplierPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='零件料號')),
                ('part_name', models.CharField(blank=True, max_length=255, verbose_name='零件品名')),
                ('fmd_tier', models.CharField(choices=[('Full FMD', 'Full FMD'), ('Partial FMD', 'Partial FMD'), ('Restricted-substance declaration', 'Restricted-substance declaration'), ('Evidence only', 'Evidence only')], default='Partial FMD', max_length=64, verbose_name='宣告等級')),
                ('rohs_status', models.CharField(choices=[('Approved', 'Approved (合格)'), ('Blocked', 'Blocked (違規禁售)'), ('Data gap', 'Data gap (資料缺口)'), ('Review', 'Review (需人工審查/SCIP)')], default='Data gap', max_length=32, verbose_name='RoHS 狀態')),
                ('reach_status', models.CharField(choices=[('Approved', 'Approved (合格)'), ('Blocked', 'Blocked (違規禁售)'), ('Data gap', 'Data gap (資料缺口)'), ('Review', 'Review (需人工審查/SCIP)')], default='Data gap', max_length=32, verbose_name='REACH SVHC 狀態')),
                ('pfas_status', models.CharField(choices=[('Approved', 'Approved (合格)'), ('Blocked', 'Blocked (違規禁售)'), ('Data gap', 'Data gap (資料缺口)'), ('Review', 'Review (需人工審查/SCIP)')], default='Data gap', max_length=32, verbose_name='PFAS 狀態')),
                ('overall_status', models.CharField(choices=[('Approved', 'Approved (合格)'), ('Blocked', 'Blocked (違規禁售)'), ('Data gap', 'Data gap (資料缺口)'), ('Review', 'Review (需人工審查/SCIP)')], default='Data gap', max_length=32, verbose_name='整體合規狀態')),
                ('raw_csv', models.TextField(blank=True, verbose_name='原始 CSV 內容')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='fmd_core.supplier', verbose_name='供應商')),
            ],
            options={
                'verbose_name': '供應商零件',
                'verbose_name_plural': '零件合規主檔',
            },
        ),
        migrations.CreateModel(
            name='ReviewTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='問題摘要')),
                ('severity', models.CharField(choices=[('blocked', '阻擋 (Blocked)'), ('data-gap', '資料缺口 (Data Gap)'), ('review', '人工審查 (Review)')], default='data-gap', max_length=32, verbose_name='嚴重等級')),
                ('remediation_instruction', models.TextField(verbose_name='具體補件 / 改善指示')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已解決')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fmd_core.homogeneousmaterial', verbose_name='關聯材料')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_tasks', to='fmd_core.supplierpart', verbose_name='關聯零件')),
            ],
            options={
                'verbose_name': '審查任務',
                'verbose_name_plural': '審查與補件佇列',
            },
        ),
        migrations.AddField(
            model_name='homogeneousmaterial',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='fmd_core.supplierpart', verbose_name='所屬零件'),
        ),
        migrations.AlterUniqueTogether(
            name='homogeneousmaterial',
            unique_together={('part', 'material_id')},
        ),
    ]
