# Generated by Django 5.1.15 on 2026-09-03 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmd_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homogeneousmaterial',
            options={'verbose_name': 'Homogeneous Material', 'verbose_name_plural': 'Homogeneous Materials'},
        ),
        migrations.AlterModelOptions(
            name='regulatoryrule',
            options={'verbose_name': 'Regulatory Rule', 'verbose_name_plural': 'Regulatory Rules'},
        ),
        migrations.AlterModelOptions(
            name='reviewtask',
            options={'verbose_name': 'Review Task', 'verbose_name_plural': 'Review Tasks'},
        ),
        migrations.AlterModelOptions(
            name='substancedeclaration',
            options={'verbose_name': 'Substance Declaration', 'verbose_name_plural': 'Substance Declarations'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterModelOptions(
            name='supplierpart',
            options={'verbose_name': 'Supplier Part', 'verbose_name_plural': 'Supplier Parts'},
        ),
        migrations.AlterField(
            model_name='homogeneousmaterial',
            name='mass_balance_valid',
            field=models.BooleanField(default=False, verbose_name='Mass Balance Valid (98%-102%)'),
        ),
        migrations.AlterField(
            model_name='homogeneousmaterial',
            name='mass_g',
            field=models.FloatField(default=0.0, verbose_name='Material Mass (g)'),
        ),
        migrations.AlterField(
            model_name='homogeneousmaterial',
            name='material_id',
            field=models.CharField(max_length=64, verbose_name='Material ID'),
        ),
        migrations.AlterField(
            model_name='homogeneousmaterial',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Material Name'),
        ),
        migrations.AlterField(
            model_name='homogeneousmaterial',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='fmd_core.supplierpart', verbose_name='Parent Part'),
        ),
        migrations.AlterField(
            model_name='homogeneousmaterial',
            name='total_concentration_pct',
            field=models.FloatField(default=0.0, verbose_name='Total Disclosed Conc. (%)'),
        ),
        migrations.AlterField(
            model_name='regulatoryrule',
            name='cas',
            field=models.CharField(db_index=True, max_length=32, verbose_name='CAS Number'),
        ),
        migrations.AlterField(
            model_name='regulatoryrule',
            name='exemption_code',
            field=models.CharField(blank=True, max_length=64, verbose_name='Applicable Exemption Code'),
        ),
        migrations.AlterField(
            model_name='regulatoryrule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='regulatoryrule',
            name='is_pfas',
            field=models.BooleanField(default=False, verbose_name='Is PFAS'),
        ),
        migrations.AlterField(
            model_name='regulatoryrule',
            name='is_svhc',
            field=models.BooleanField(default=False, verbose_name='Is REACH SVHC'),
        ),
        migrations.AlterField(
            model_name='regulatoryrule',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Legal Citations / Regulatory Notes'),
        ),
        migrations.AlterField(
            model_name='regulatoryrule',
            name='regulation',
            field=models.CharField(choices=[('EU RoHS', 'EU RoHS Directive 2011/65/EU'), ('REACH SVHC', 'EU REACH Candidate List (SVHC)'), ('PFAS', 'PFAS Universal / Group Restrictions'), ('China RoHS', 'China RoHS (SJ/T 11364)'), ('Prop 65', 'California Proposition 65')], max_length=64, verbose_name='Regulation'),
        ),
        migrations.AlterField(
            model_name='regulatoryrule',
            name='substance_name',
            field=models.CharField(max_length=255, verbose_name='Substance Name'),
        ),
        migrations.AlterField(
            model_name='regulatoryrule',
            name='threshold_pct',
            field=models.FloatField(blank=True, null=True, verbose_name='Threshold Limit (%)'),
        ),
        migrations.AlterField(
            model_name='regulatoryrule',
            name='version',
            field=models.CharField(default='2026.09', max_length=64, verbose_name='Rule Version'),
        ),
        migrations.AlterField(
            model_name='reviewtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='reviewtask',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='Is Resolved'),
        ),
        migrations.AlterField(
            model_name='reviewtask',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fmd_core.homogeneousmaterial', verbose_name='Associated Material'),
        ),
        migrations.AlterField(
            model_name='reviewtask',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_tasks', to='fmd_core.supplierpart', verbose_name='Associated Part'),
        ),
        migrations.AlterField(
            model_name='reviewtask',
            name='remediation_instruction',
            field=models.TextField(verbose_name='Actionable Remediation Instruction'),
        ),
        migrations.AlterField(
            model_name='reviewtask',
            name='severity',
            field=models.CharField(choices=[('blocked', 'Blocked (Critical Exceedance)'), ('data-gap', 'Data Gap (Missing Chemistry / Evidence)'), ('review', 'Review (SCIP / Article Threshold)')], default='data-gap', max_length=32, verbose_name='Severity'),
        ),
        migrations.AlterField(
            model_name='reviewtask',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Task Title'),
        ),
        migrations.AlterField(
            model_name='substancedeclaration',
            name='action_required',
            field=models.TextField(blank=True, verbose_name='Actionable Instruction'),
        ),
        migrations.AlterField(
            model_name='substancedeclaration',
            name='cas',
            field=models.CharField(db_index=True, max_length=32, verbose_name='CAS Number'),
        ),
        migrations.AlterField(
            model_name='substancedeclaration',
            name='concentration_pct',
            field=models.FloatField(verbose_name='Disclosed Conc. (%)'),
        ),
        migrations.AlterField(
            model_name='substancedeclaration',
            name='concentration_ppm',
            field=models.FloatField(default=0.0, verbose_name='Calculated Conc. (ppm)'),
        ),
        migrations.AlterField(
            model_name='substancedeclaration',
            name='evidence_status',
            field=models.CharField(default='None', max_length=64, verbose_name='Evidence Document Status'),
        ),
        migrations.AlterField(
            model_name='substancedeclaration',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substances', to='fmd_core.homogeneousmaterial', verbose_name='Parent Material'),
        ),
        migrations.AlterField(
            model_name='substancedeclaration',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Substance Name'),
        ),
        migrations.AlterField(
            model_name='substancedeclaration',
            name='pfas_eval',
            field=models.CharField(default='Approved', max_length=32, verbose_name='PFAS Verdict'),
        ),
        migrations.AlterField(
            model_name='substancedeclaration',
            name='pfas_intentional_use',
            field=models.CharField(default='Unknown', max_length=32, verbose_name='PFAS Intentional Use'),
        ),
        migrations.AlterField(
            model_name='substancedeclaration',
            name='reach_eval',
            field=models.CharField(default='Approved', max_length=32, verbose_name='REACH SVHC Verdict'),
        ),
        migrations.AlterField(
            model_name='substancedeclaration',
            name='rohs_eval',
            field=models.CharField(default='Approved', max_length=32, verbose_name='EU RoHS Verdict'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Supplier Name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='quality_score',
            field=models.FloatField(default=100.0, verbose_name='Data Quality Score'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_code',
            field=models.CharField(max_length=64, unique=True, verbose_name='Supplier Code'),
        ),
        migrations.AlterField(
            model_name='supplierpart',
            name='fmd_tier',
            field=models.CharField(choices=[('Full FMD', 'Full FMD'), ('Partial FMD', 'Partial FMD'), ('Restricted-substance declaration', 'Restricted-substance declaration'), ('Evidence only', 'Evidence only')], default='Partial FMD', max_length=64, verbose_name='Declaration Tier'),
        ),
        migrations.AlterField(
            model_name='supplierpart',
            name='overall_status',
            field=models.CharField(choices=[('Approved', 'Approved (Compliant)'), ('Blocked', 'Blocked (Non-compliant)'), ('Data gap', 'Data gap (Incomplete chemistry)'), ('Review', 'Review (SCIP / Human verification)')], default='Data gap', max_length=32, verbose_name='Overall Verdict'),
        ),
        migrations.AlterField(
            model_name='supplierpart',
            name='part_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Part Description'),
        ),
        migrations.AlterField(
            model_name='supplierpart',
            name='part_number',
            field=models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Part Number'),
        ),
        migrations.AlterField(
            model_name='supplierpart',
            name='pfas_status',
            field=models.CharField(choices=[('Approved', 'Approved (Compliant)'), ('Blocked', 'Blocked (Non-compliant)'), ('Data gap', 'Data gap (Incomplete chemistry)'), ('Review', 'Review (SCIP / Human verification)')], default='Data gap', max_length=32, verbose_name='PFAS Status'),
        ),
        migrations.AlterField(
            model_name='supplierpart',
            name='raw_csv',
            field=models.TextField(blank=True, verbose_name='Original CSV Content'),
        ),
        migrations.AlterField(
            model_name='supplierpart',
            name='reach_status',
            field=models.CharField(choices=[('Approved', 'Approved (Compliant)'), ('Blocked', 'Blocked (Non-compliant)'), ('Data gap', 'Data gap (Incomplete chemistry)'), ('Review', 'Review (SCIP / Human verification)')], default='Data gap', max_length=32, verbose_name='REACH SVHC Status'),
        ),
        migrations.AlterField(
            model_name='supplierpart',
            name='rohs_status',
            field=models.CharField(choices=[('Approved', 'Approved (Compliant)'), ('Blocked', 'Blocked (Non-compliant)'), ('Data gap', 'Data gap (Incomplete chemistry)'), ('Review', 'Review (SCIP / Human verification)')], default='Data gap', max_length=32, verbose_name='EU RoHS Status'),
        ),
        migrations.AlterField(
            model_name='supplierpart',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='fmd_core.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='supplierpart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
    ]
