# Generated by Django 5.1.15 on 2026-09-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmd_core', '0002_alter_homogeneousmaterial_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatorySyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Execution Timestamp')),
                ('triggered_by', models.CharField(default='Scheduler', max_length=64, verbose_name='Triggered By')),
                ('source_name', models.CharField(default='ECHA / IEC 62474 / Global Feeds', max_length=128, verbose_name='Authority / Feed Source')),
                ('rules_checked', models.IntegerField(default=0, verbose_name='Rules Checked')),
                ('rules_updated', models.IntegerField(default=0, verbose_name='Rules Updated / Added')),
                ('parts_revaluated', models.IntegerField(default=0, verbose_name='Parts Re-evaluated')),
                ('parts_impacted', models.IntegerField(default=0, verbose_name='Parts Impacted')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Structured Audit Details')),
                ('status', models.CharField(default='Success', max_length=32, verbose_name='Sync Status')),
            ],
            options={
                'verbose_name': 'Regulatory Sync Log',
                'verbose_name_plural': 'Regulatory Sync Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='regulatoryrule',
            name='effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='Effective Date'),
        ),
        migrations.AddField(
            model_name='regulatoryrule',
            name='source_url',
            field=models.CharField(blank=True, max_length=512, verbose_name='Official Source URL'),
        ),
        migrations.AlterField(
            model_name='regulatoryrule',
            name='regulation',
            field=models.CharField(choices=[('EU RoHS', 'EU RoHS Directive 2011/65/EU'), ('REACH SVHC', 'EU REACH Candidate List (SVHC)'), ('PFAS', 'PFAS Universal / Group Restrictions'), ('Taiwan RoHS', 'Taiwan RoHS (CNS 15663 / BSMI)'), ('TSCA', 'US EPA TSCA (Section 6/8)'), ('China RoHS', 'China RoHS (SJ/T 11364)'), ('Prop 65', 'California Proposition 65')], max_length=64, verbose_name='Regulation'),
        ),
    ]
