# Generated by Django 5.1.15 on 2026-09-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmd_core', '0003_regulatorysynclog_regulatoryrule_effective_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpart',
            name='cbi_attested',
            field=models.BooleanField(default=False, verbose_name='CBI Non-Hazardous Attested'),
        ),
    ]
