# Generated by Django 5.1.15 on 2026-09-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmd_core', '0004_supplierpart_cbi_attested'),
    ]

    operations = [
        migrations.AddField(
            model_name='substancedeclaration',
            name='exemption',
            field=models.CharField(blank=True, default='None', max_length=32, verbose_name='RoHS Exemption'),
        ),
    ]
