# Generated by Django 5.1.15 on 2026-09-11 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmd_core', '0005_substancedeclaration_exemption'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField(default=1, verbose_name='Revision Number')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='Uploaded File Name')),
                ('fmd_tier', models.CharField(default='Full FMD', max_length=64, verbose_name='Declaration Tier')),
                ('overall_status', models.CharField(default='Data gap', max_length=32, verbose_name='Overall Verdict')),
                ('rohs_status', models.CharField(default='Data gap', max_length=32, verbose_name='RoHS Status')),
                ('reach_status', models.CharField(default='Data gap', max_length=32, verbose_name='REACH Status')),
                ('pfas_status', models.CharField(default='Data gap', max_length=32, verbose_name='PFAS Status')),
                ('cbi_detected', models.BooleanField(default=False, verbose_name='CBI Detected')),
                ('cbi_attested', models.BooleanField(default=False, verbose_name='CBI Attested')),
                ('snapshot_data', models.JSONField(default=dict, verbose_name='Composition Snapshot JSON')),
                ('raw_csv', models.TextField(blank=True, verbose_name='Raw File Content')),
                ('change_summary', models.TextField(blank=True, verbose_name='Revision Notes / Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='fmd_core.supplierpart', verbose_name='Parent Part')),
            ],
            options={
                'verbose_name': 'Part Revision',
                'verbose_name_plural': 'Part Revisions',
                'ordering': ['-revision_number'],
            },
        ),
    ]
